name: PR build

on:
  push:
    branches-ignore:
      - 'main'
  pull_request:
    branches-ignore:
      - 'main'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
        check-latest: true

    - name: Build
      run: go build -v ./...

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.0

    - name: Run golangci-lint
      run: golangci-lint run --version --verbose

    - name: Run govulncheck
      uses: golang/govulncheck-action@v1

